mv name.extension arch_indices.txt
mv name.extension elements_by_faces.txt
mv name.extension elements_by_vertices_repeated.txt
mv name.extension elements_by_vertices.txt
mv name.extension elements.txt
mv name.extension faces_local_to_global.txt
mv name.extension faces_repeated.txt
mv name.extension faces.txt
mv name.extension num_faces.txt
mv name.extension vertices.txt
